# Nova Snakemake Pipeline Configuration

# Input files (REQUIRED)
bam_file: "tests/test_data/test_reads.bam"                                            # Path to input BAM file
reference_genome: "/Users/stacy/sudmant/references/hg38_HGSVC/hg38.no_alt.fa.gz"      # Path to reference genome FASTA
repeats: "/Users/stacy/sudmant/references/hg38_HGSVC/GRCh38_simpleRepeat.bed"
variant_config: "ten_reads_per_window.json"                                                 # Path to variant config

# Output settings
output_dir: "ten_reads_per_window"
output_prefix: "nova"

# Read selection parameters
random_seed: 42                  # Random seed for subsampling
subsample_fraction: 0.001       # Fraction of reads to subsample (0.0-1.0)
min_mapq: 20                     # Minimum mapping quality
max_soft_clip_ratio: 0.1         # Maximum soft clipping ratio
min_read_length: 10000           # Minimum read length
max_read_length: 20000           # Maximum read length
min_distance_from_ends: 1000     # Minimum distance from read ends for insertion
max_reads_per_window: 10          # Maximum reads per genomic window

# Variant calling parameters
minsupport: 0
mapq: 20
mosaic_af_min: 0
mosaic_af_max: 0.2
mosaic_qc_strand: False