name: nova
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - pysam>=0.19.0
  - bedtools>=2.30.0
  - numpy>=1.20.0
  - biopython>=1.79
  - click>=8.0.0
  - samtools>=1.15
  - bcftools>=1.15
  - minimap2
  - pytest>=6.0.0
  - pytest-cov>=2.12.0