name: nova
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - pip==25.1.1
  - uv==0.6.11
  - bedtools==2.31.1
  - samtools==1.22
  - bcftools==1.22
  - minimap2==2.30
  - sniffles==2.6.1
  - truvari==5.3.0
  - snakemake-minimal==9.6.2
  - setuptools==80.9.0 # note: flagged for deprecation, dependency of pyranges
  - biopython==1.85
  - pysam==0.23.3
  - pandas==2.3.0
  - numpy==2.3.1
  - pyranges==0.1.4
  - rich-click==1.8.9
  - pytest==8.4.1
  - matplotlib==3.10.3
  - seaborn==0.13.2