# Nova Snakemake Pipeline Configuration

# Input files (REQUIRED)
bam_file: "input.bam"                    # Path to input BAM file
reference_genome: "reference.fasta"      # Path to reference genome FASTA
variant_config: "variant_config.json"       # Path to variant config

# Output settings
output_dir: "results"
output_prefix: "output/nova"

# Read selection parameters
random_seed: 42                  # Random seed for subsampling
subsample_fraction: 0.001       # Fraction of reads to subsample (0.0-1.0)
min_mapq: 20                     # Minimum mapping quality
max_soft_clip_ratio: 0.1         # Maximum soft clipping ratio
min_read_length: 10000           # Minimum read length
max_read_length: 20000           # Maximum read length
min_distance_from_ends: 1000     # Minimum distance from read ends for insertion